### ISSUE TITLE
InputService Injection fails due to WinRT error on the constructor

### ISSUE THREAD

**Issue by nir-schleyen** [WatchBeam/arcade-machine#60]
This is the error we were getting:
- “ERROR WinRTError: The application called an interface that was marshalled for a different thread.”

This is the "TEMPORARY" fix we had to put in (assigning null):

/**
 * InputService handles passing input from the external device (gamepad API
 * or keyboard) to the arc internals.
 */
var InputService = (function () {
    function InputService(focus) {
        this.focus = focus;
        /**
         * Inputpane and boolean to indicate whether it's visible
         */
        **this.inputPane = null;// window.Windows ? Windows.UI.ViewManagement.InputPane.getForCurrentView() : null;**

**Comment by connor4312** [comment]
Hi @nir-schleyen. In the conext of our web application, we've not come across this issue. Others might know more but I am unsure if that's even reproducible in a hosted UWP web app. Can you advise to what your ideal fix would be here? Perhaps [L421](https://github.com/WatchBeam/arcade-machine/blob/master/src/input.service.ts#L241) should read something like this:

```js
  public get keyboardVisible(): boolean {
    let inputPane: Windows.UI.ViewManagement.InputPane;
    try {
      inputPane = Windows.UI.ViewManagement.InputPane.getForCurrentView();
    } catch (_e) {
      return false;
    }
    
    return inputPane.occludedRect.y !== 0 ||inputPane.visible;
  }
```

**Comment by saadataz** [comment]
@connor4312 This exception appears to be thrown here](https://github.com/WatchBeam/arcade-machine/blob/master/src/input.service.ts#L234) when you try to access `Windows.UI.ViewManagement.InputPane.getForCurrentView()` from inside a webview (separate thread) in a UWP app.
We can add a try block there.

**Comment by connor4312** [comment]
Yea, I'm saying remove that and just use a 'runtime' lookup in keyboardVisible.

There's some more discussion in a mail thread 😄
